# Generated by Django 3.0.5 on 2020-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200509_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('active', 'active'), ('ended', 'ended')], default='upcoming', max_length=10),
        ),
    ]
