# Generated by Django 3.0.5 on 2020-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='actual_length',
            field=models.IntegerField(default=0),
        ),
    ]
